
services:

  db:
    image: postgres:14.0-alpine
    container_name: db
    hostname: db
    restart: unless-stopped
    volumes:
      - ./db/data/:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: contentapi
      POSTGRES_USER: django
      POSTGRES_PASSWORD: django
    ports:
      - 5432:5432
    expose:
      - 5432

  redis:
    restart: on-failure
    image: redis:7.2.1
    hostname: redis
    container_name: redis
    ports:
      - 6379:6379
    expose:
      - 6379

  app:
    container_name: contentapi
    hostname: app
    build:
      context: .
      dockerfile: DockerFile
    restart: unless-stopped
    command: "python src/manage.py runserver 0.0.0.0:3000"
    ports:
      - "3000:3000"
    expose:
      - 3000
    depends_on:
      - db
      - redis
    volumes:
      - type: bind
        source: ./src
        target: /src
    environment:
      DATABASE_URL: postgres://django:django@db/contentapi
      REDIS_URL: redis://redis:6379/1